# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:43
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tickets.SpecificItem'),
            preserve_default=False,
        ),
    ]
