# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 13:54
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0002_ticket_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='expiry_date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 6, 18, 13, 54, 52, 625885),
                                   verbose_name='expiry date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignment_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='assignment date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
