# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20160618_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignment_date',
            field=models.DateField(blank=True, null=True, verbose_name='assignment date'),
        ),
    ]
