# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20160620_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('PROBLEM', 'probleem oplossen'), ('INSTALLATION', 'instalatie'), ('MAINTENANCE', 'onderhoud')], default='PROBLEM', max_length=255),
        ),
    ]
