# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'default_permissions': ('add', 'change', 'delete', 'view')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='close date'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.Part'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ServiceContract'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN PROGRESS', 'In Behandeling'), ('CLOSED', 'Gesloten')], default='OPEN', max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('PROBLEM', 'Probleem Oplossen'), ('INSTALLATION', 'Instalatie'), ('MAINTENANCE', 'Onderhoud'), ('REINSTALL', 'Herinstallatie')], default='PROBLEM', max_length=255),
        ),
    ]
