# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 11:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0006_auto_20160709_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='service_contract',
        ),
        migrations.AddField(
            model_name='item',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='tickets.ServiceContract'),
        ),
        migrations.AddField(
            model_name='part',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.Item'),
            preserve_default=False,
        ),
    ]
