# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tickets', '0007_auto_20160713_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='assignment date'),
        ),
    ]
